[2025-03-05T23:59:45.707+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T23:59:45.773+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.create_table_postgres manual__2025-03-05T23:59:40.728320+00:00 [queued]>
[2025-03-05T23:59:45.797+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load_data_to_elastic_search_rag.create_table_postgres manual__2025-03-05T23:59:40.728320+00:00 [queued]>
[2025-03-05T23:59:45.798+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-05T23:59:45.832+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_table_postgres> on 2025-03-05 23:59:40.728320+00:00
[2025-03-05T23:59:45.866+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T23:59:45.857+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Load_data_to_elastic_search_rag', 'create_table_postgres', 'manual__2025-03-05T23:59:40.728320+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp1n4u4baq']
[2025-03-05T23:59:45.871+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask create_table_postgres
[2025-03-05T23:59:45.871+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2025-03-05T23:59:46.178+0000] {task_command.py:467} INFO - Running <TaskInstance: Load_data_to_elastic_search_rag.create_table_postgres manual__2025-03-05T23:59:40.728320+00:00 [running]> on host 67763114dcf0
[2025-03-05T23:59:46.588+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Artur Tiburski' AIRFLOW_CTX_DAG_ID='Load_data_to_elastic_search_rag' AIRFLOW_CTX_TASK_ID='create_table_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T23:59:40.728320+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T23:59:40.728320+00:00'
[2025-03-05T23:59:46.592+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T23:59:46.762+0000] {logging_mixin.py:190} INFO - relation "all_documents" already exists
[2025-03-05T23:59:46.764+0000] {logging_mixin.py:190} INFO - current transaction is aborted, commands ignored until end of transaction block
[2025-03-05T23:59:46.766+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T23:59:46.815+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T23:59:46.816+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Load_data_to_elastic_search_rag, task_id=create_table_postgres, run_id=manual__2025-03-05T23:59:40.728320+00:00, execution_date=20250305T235940, start_date=20250305T235945, end_date=20250305T235946
[2025-03-05T23:59:46.899+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T23:59:47.046+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T23:59:47.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
